/**
 * Seeds a Supabase project with the same fictional demo data the local mode uses.
 *
 *   npx tsx scripts/seed-supabase.ts --sql > supabase/seed.sql
 *       Prints SQL for the reference tables (providers, availability, programs).
 *       Dates are expressed relative to the next demo surgery day, so the file
 *       never goes stale.
 *
 *   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... npx tsx scripts/seed-supabase.ts
 *       Creates the demo auth users (password "demo"), profiles, patients,
 *       caregivers, instructions and reference data, then runs the deterministic
 *       plan for each patient. Service role only; never run from a client.
 */
import { createClient } from '@supabase/supabase-js';
import { formatInTimeZone } from 'date-fns-tz';
import { refreshPlan } from '@/core/usecases';
import { buildDemoStore, DEMO_TZ } from '@/data/local/seed';
import { SupabaseRepository } from '@/data/supabase/SupabaseRepository';

const snake = (s: string) => s.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`);
const toRow = (o: object) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined).map(([k, v]) => [snake(k), v]));

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return `array[${v.map(sqlLiteral).join(',')}]::text[]`;
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

function printSql() {
  const now = new Date();
  const store = buildDemoStore(now);
  const surgeryDay = store.patients[0].surgeryDate;
  const surgeryKey = formatInTimeZone(new Date(surgeryDay), DEMO_TZ, 'yyyy-MM-dd');
  const dayOffset = (iso: string) => Math.round((Date.parse(formatInTimeZone(new Date(iso), DEMO_TZ, 'yyyy-MM-dd')) - Date.parse(surgeryKey)) / 86_400_000);
  const rel = (iso: string) => `((cb_demo_surgery_day() + ${dayOffset(iso)}) + time '${formatInTimeZone(new Date(iso), DEMO_TZ, 'HH:mm')}') at time zone '${DEMO_TZ}'`;

  const lines: string[] = [
    '-- Generated by scripts/seed-supabase.ts --sql. Fictional reference data only.',
    '-- Patients, caregivers and instructions need auth users: run the script without --sql for those.',
    '',
    '-- Next Friday at least two days out, in the demo time zone (matches src/data/local/seed.ts).',
    'create or replace function cb_demo_surgery_day() returns date language sql stable as $$',
    `  select d::date from generate_series((now() at time zone '${DEMO_TZ}')::date + 2, (now() at time zone '${DEMO_TZ}')::date + 9, interval '1 day') d where extract(dow from d) = 5 limit 1`,
    '$$;',
    '',
    'delete from provider_availability; delete from service_requests; delete from assistance_requests;',
    'delete from provider_companies; delete from assistance_programs;',
    '',
  ];
  const insert = (table: string, rows: Record<string, unknown>[], override: Record<string, (r: Record<string, unknown>) => string> = {}) => {
    for (const r of rows) {
      const cols = Object.keys(r);
      const vals = cols.map((c) => (override[c] ? override[c](r) : sqlLiteral(r[c])));
      lines.push(`insert into ${table} (${cols.join(', ')}) values (${vals.join(', ')});`);
    }
    lines.push('');
  };
  insert('provider_companies', store.providers.map(toRow));
  insert(
    'provider_availability',
    store.providerAvailability.map(toRow),
    { start_at: (r) => rel(String(r.start_at)), end_at: (r) => rel(String(r.end_at)) },
  );
  insert('assistance_programs', store.programs.map(toRow));
  process.stdout.write(lines.join('\n'));
}

async function push() {
  const url = process.env.SUPABASE_URL ?? process.env.EXPO_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
  const db = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  const store = buildDemoStore(new Date());

  // 1. Auth users (idempotent: reuse if the email exists).
  const { data: existing } = await db.auth.admin.listUsers({ perPage: 1000 });
  const authIdFor = async (email: string) => {
    const found = existing?.users.find((u) => u.email?.toLowerCase() === email);
    if (found) return found.id;
    const { data, error } = await db.auth.admin.createUser({ email, password: 'demo', email_confirm: true });
    if (error || !data.user) throw new Error(error?.message ?? 'createUser failed');
    return data.user.id;
  };
  for (const p of store.profiles) {
    const acct = store.accounts.find((a) => a.profileId === p.id);
    p.authUserId = await authIdFor(acct?.email ?? `${p.id}@demo.carebridge`);
  }

  const ins = async (table: string, rows: object[]) => {
    if (!rows.length) return;
    const { error } = await db.from(table).upsert(rows.map(toRow));
    if (error) throw new Error(`${table}: ${error.message}`);
    console.log(`${table}: ${rows.length}`);
  };

  // 2. Clear derived rows for the demo patients (task_events cascade from tasks), then insert in dependency order.
  const patientIds = store.patients.map((p) => p.id);
  await db.from('notifications').delete().in('recipient_id', store.profiles.map((p) => p.id));
  for (const t of ['recovery_tasks', 'recovery_gaps', 'recovery_requirements', 'service_requests', 'assistance_requests', 'clinical_reviews']) {
    const { error } = await db.from(t).delete().in('patient_id', patientIds);
    if (error) throw new Error(`${t}: ${error.message}`);
  }
  await ins('profiles', store.profiles);
  await ins('patients', store.patients);
  await ins('patient_equipment', store.equipment);
  await ins('caregivers', store.caregivers);
  await ins('caregiver_availability', store.availability);
  await ins('discharge_documents', store.documents);
  await ins('clinical_instructions', store.instructions);
  await ins('provider_companies', store.providers);
  await ins('provider_availability', store.providerAvailability);
  await ins('assistance_programs', store.programs);

  // 3. Run the deterministic engines once so requirements, gaps and tasks exist.
  const repo = new SupabaseRepository(db);
  for (const p of store.patients) {
    const r = await refreshPlan(repo, p.id);
    console.log(`${p.displayName}: ${r.readiness.gaps.length} gaps, ${r.calendar.tasks.length} tasks, status ${r.readiness.status}`);
  }
  console.log('Done. Demo logins: maria@demo.carebridge, sofia@demo.carebridge, jordan@demo.carebridge, james@demo.carebridge (password: demo)');
}

if (process.argv.includes('--sql')) printSql();
else push().catch((e) => {
  console.error(e);
  process.exit(1);
});
